# Generated by Django 3.2.5 on 2021-08-01 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person_manag', '0002_auto_20210801_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupperson',
            name='Name_Group',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
