# Generated by Django 3.2.5 on 2021-08-01 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person_manag', '0004_auto_20210801_2136'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_Group', models.CharField(blank=True, max_length=30)),
            ],
        ),
    ]
