# Generated by Django 3.2.5 on 2021-08-01 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person_manag', '0005_groupperson'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='person_group',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='person_manag.groupperson'),
            preserve_default=False,
        ),
    ]
