# Generated by Django 3.2.5 on 2021-08-02 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person_manag', '0006_customuser_person_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='person_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_group', to='person_manag.groupperson'),
        ),
    ]
