# Generated by Django 3.2.5 on 2021-08-02 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person_manag', '0007_alter_customuser_person_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='person_group',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='person_manag.groupperson'),
        ),
    ]
