# Generated by Django 3.2.5 on 2021-08-05 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person_manag', '0009_auto_20210804_1553'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='FIO',
            new_name='fio',
        ),
    ]
